### PR TITLE
Search branch

### PR DESCRIPTION
**Pull request by KataBoku**
This branch closes issues for classification/ disambiguation / relationship suggestions. It closes issues # 192, # 150, # 147, # 148. But it also closes issues # 207 and corrects the focus on selectboxes as a side effect.

### CODE REVIEW

**Comment by tomas-knap** [comment]
@KataBoku Thanks! Please solve the conflicts (by merging Develop into this branch). This is always a good practise, so that the code reviewer (@istvan-satmari) does not need to do that on his own.

**Comment by brodecva** [comment]
Hi, @KataBoku , I tried to look at the changes so far, but the properties dialog does not show up. It is indeed broken as it is now, as you warned. Ping me, when the errors caused by resolving the conflicts during the merge are fixed.

**Comment by brodecva** [comment]
@KataBoku Hi, any progress?

**Comment by KataBoku** [comment]
I solved merge conflicts.  And I have never had problems with dialogues.

**Comment by brodecva** [comment]
@KataBoku Thanks! I have some minor grips, but otherwise the main problems seem to be resolved.

**Comment by tomas-knap** [comment]
@brodecva Please write down the minor issues to a new task or grips page (if you think they are really nice to have). It does not necessary mean we will realize them, but it is good to know about them.

**Comment by brodecva** [comment]
@tomas-knap I have already done so: #225 and #224 .

**Pull request merged**
