### PR TITLE
Kb management

### PR DESCRIPTION
**Pull request by brodecva**

### CODE REVIEW

**Comment by brodecva** [comment]
First batch of issues, may lead to separate issues:

- Add and import button to close to each other.
- After group adding or modyfing, it does not return to Search tab.
- Tooltips missing.

**Comment by brodecva** [comment]
- Missing leading text to the Autodetect button, also move it immediately after the (now missing) description from the far right where it can be easily overlooked.

**Comment by brodecva** [comment]
- The valid values in Method are Exact, Fulltext and Substring. With Fulltext as the default. (I have added this to the REST specs.

**Comment by brodecva** [comment]
Hi, another one:
- When implementing defaults, I have noticed that there is no general rule that all parts (class types, property predicates,...) in a group must have at least one entry, some of these are often left empty actually. So please relax this restriction, as I have done on the server. Also @JanVana might chime in to tell us, which of the "enum" properties must be always present (or if the rule is that at least one of the enums has to "cover" the part), if any.

**Comment by brodecva** [comment]
- The advanced properties comments should be read only. They are defined within the advanced type definition along the default values. Basically the key-value display should pre-display the keys defined within the the advanced type, and their default values, if present (editable), and the comments (if present) as read only. Hope it is clear now. I will create some testing advanced type for you to test, because the SPARQL one will not have any.

**Comment by istvan-satmari** [comment]
Most  of them done; as for tooltips, I do not understand - there already are tooltips over the action icons. Where else would you like to have them?

**Pull request merged**
